# Generated by Django 3.1.7 on 2021-04-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_input_test', '0002_auto_20210401_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='gf',
            new_name='group_former',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='gf',
            new_name='group_former',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='gf',
            new_name='group_former',
        ),
    ]
