# Generated by Django 3.1.7 on 2021-04-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_input_test', '0004_auto_20210401_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='name',
            new_name='attr_name',
        ),
    ]
