# Generated by Django 3.1.7 on 2021-04-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_input_test', '0005_auto_20210401_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='desired_partner',
            field=models.ManyToManyField(blank=True, to='project_input_test.Participant'),
        ),
    ]
