# Generated by Django 3.1.7 on 2021-04-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbtools', '0003_auto_20210415_0338'),
        ('dbtools', '0003_auto_20210414_2145'),
    ]

    operations = [
    ]
