# Generated by Django 3.1.7 on 2021-04-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(),
        ),
    ]
